name = "eml"
description = "EML compiler and interpreter"
version = "1.0"

authors = ["Stefano Anelli"]
maintainers = ["Stefano Anelli <redacted@redacted.com>"]
maintainers-logins = ["sanelli"]
licenses = "MIT"
website = ""
tags = ["eml", "compiler", "interpreter"]

executables = ["eml", "eml_tests"]

[[actions]]
type = "pre-build"
command = ["pwsh", "-NoProfile", "-File", "scripts/embed_git_commit.ps1"]

[build-switches]
"*".ada_version = "Ada2022"
"*".compile_checks = "Errors"
"*".contracts = "Yes"
"*".runtime_checks = "Everything"
"*".style_checks = "Yes"
"*".source_encoding = "utf_8"
development.optimization = "Debug"
development.debug_info = "Yes"
validation.compile_checks = "Errors"
validation.style_checks = "Yes"
validation.runtime_checks = "Everything"
release.compile_checks = "Errors"
release.style_checks = "Yes"
