# Embed the current short git commit into src/eml_git_commit.ads.
$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $PSScriptRoot
try {
    $Commit = (git -C $Root rev-parse --short HEAD 2>$null).Trim()
    if (-not $Commit) { $Commit = "unknown" }
} catch {
    $Commit = "unknown"
}

$Content = @"
--  Build-time git commit; generated by scripts/embed_git_commit.ps1.
package Eml_Git_Commit is

   Commit : constant String := "$Commit";

end Eml_Git_Commit;
"@

Set-Content -Path (Join-Path $Root "src/eml_git_commit.ads") -Value $Content -Encoding utf8NoBOM
